# After that, you can edit ~/.aerospace.toml to your liking

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
  'exec-and-forget /opt/homebrew/bin/borders active_color=0xFFF9E2AF inactive_color=0xff494d64 width=5.0'
]
# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = "move-mouse window-lazy-center"

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodness#disable-hide-app
automatically-unhide-macos-hidden-apps = true

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with alt + enter shortcut (like in i3)
#ctrl-alt-cmd-z = 'exec-and-forget open -n /Applications/Firefox.app'
ctrl-alt-cmd-g = '''exec-and-forget 
pgrep -x "firefox" > /dev/null && /Applications/Firefox.app/Contents/MacOS/firefox --new-window || firefox &
osascript -e 'tell application "Firefox" to activate'
'''

ctrl-alt-cmd-enter = '''exec-and-forget 
ps aux | grep -q "[w]ezterm-gui" > /dev/null && /Applications/Wezterm.app/Contents/MacOS/wezterm-gui || wezterm-gui &
osascript -e 'tell application "wezterm-gui" to activate'
'''

ctrl-alt-cmd-v = '''exec-and-forget osascript -e '
tell application "Finder"
    set newWindow to make new Finder window
    set target of newWindow to POSIX file "/Users/reed/Downloads"
    activate
end tell'
'''

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
ctrl-alt-cmd-slash = 'layout tiles horizontal vertical'
ctrl-alt-cmd-minus = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
ctrl-alt-cmd-h = 'focus left'
ctrl-alt-cmd-a = 'focus down'
ctrl-alt-cmd-o = 'focus up'
ctrl-alt-cmd-e = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
ctrl-alt-cmd-shift-h = 'move left'
ctrl-alt-cmd-shift-a = 'move down'
ctrl-alt-cmd-shift-o = 'move up'
ctrl-alt-cmd-shift-e = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
ctrl-alt-cmd-f = 'resize smart -50'
ctrl-alt-cmd-u = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
#ctrl-alt-cmd-1 = 'workspace 1'
#ctrl-alt-cmd-2 = 'workspace 2'
#ctrl-alt-cmd-3 = 'workspace 3'
#ctrl-alt-cmd-4 = 'workspace 4'
#ctrl-alt-cmd-5 = 'workspace 5'
#ctrl-alt-cmd-6 = 'workspace 6'
#ctrl-alt-cmd-7 = 'workspace 7'
#ctrl-alt-cmd-8 = 'workspace 8'
#ctrl-alt-cmd-9 = 'workspace 9'
#ctrl-alt-cmd-h = 'workspace H'
#ctrl-alt-cmd-a = 'workspace A' # In your config, you can drop workspace bindings that you don't need
#ctrl-alt-cmd-c = 'workspace C'
#ctrl-alt-cmd-e = 'workspace E'
#ctrl-alt-cmd-i = 'workspace I'
#ctrl-alt-cmd-f = 'workspace F'
#ctrl-alt-cmd-o = 'workspace O'
#ctrl-alt-cmd-u = 'workspace U'
#ctrl-alt-cmd-j = 'workspace J'
ctrl-alt-cmd-b = 'workspace B'
#ctrl-alt-cmd-c = 'workspace C'
ctrl-alt-cmd-d = 'workspace D'
#ctrl-alt-cmd-g = 'workspace G'
ctrl-alt-cmd-l = 'workspace L'
# ctrl-alt-cmd-m = 'workspace M'
ctrl-alt-cmd-n = 'workspace N'
#ctrl-alt-cmd-p = 'workspace P'
# ctrl-alt-cmd-q = 'workspace Q'
ctrl-alt-cmd-r = 'workspace R'
ctrl-alt-cmd-s = 'workspace S'
ctrl-alt-cmd-t = 'workspace T'
# ctrl-alt-cmd-v = 'workspace V'
ctrl-alt-cmd-w = 'workspace W'
# ctrl-alt-cmd-x = 'workspace X'
#ctrl-alt-cmd-y = 'workspace Y'
#ctrl-alt-cmd-z = 'workspace Z'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
#ctrl-alt-cmd-shift-1 = 'move-node-to-workspace 1'
#ctrl-alt-cmd-shift-2 = 'move-node-to-workspace 2'
#ctrl-alt-cmd-shift-3 = 'move-node-to-workspace 3'
#ctrl-alt-cmd-shift-4 = 'move-node-to-workspace 4'
#ctrl-alt-cmd-shift-5 = 'move-node-to-workspace 5'
#ctrl-alt-cmd-shift-6 = 'move-node-to-workspace 6'
#ctrl-alt-cmd-shift-7 = 'move-node-to-workspace 7'
#ctrl-alt-cmd-shift-8 = 'move-node-to-workspace 8'
#ctrl-alt-cmd-shift-9 = 'move-node-to-workspace 9'
#ctrl-alt-cmd-shift-a = 'move-node-to-workspace A'
ctrl-alt-cmd-shift-b = 'move-node-to-workspace B'
#ctrl-alt-cmd-shift-c = 'move-node-to-workspace C'
ctrl-alt-cmd-shift-d = 'move-node-to-workspace D'
#ctrl-alt-cmd-shift-e = 'move-node-to-workspace E'
#ctrl-alt-cmd-shift-f = 'move-node-to-workspace F'
#ctrl-alt-cmd-shift-g = 'move-node-to-workspace G'
#ctrl-alt-cmd-shift-h = 'move-node-to-workspace H'
#ctrl-alt-cmd-shift-i = 'move-node-to-workspace I'
#ctrl-alt-cmd-shift-j = 'move-node-to-workspace J'
ctrl-alt-cmd-shift-l = 'move-node-to-workspace L'
#ctrl-alt-cmd-shift-m = 'move-node-to-workspace M'
ctrl-alt-cmd-shift-n = 'move-node-to-workspace N'
#ctrl-alt-cmd-shift-o = 'move-node-to-workspace O'
#ctrl-alt-cmd-shift-p = 'move-node-to-workspace P'
#ctrl-alt-cmd-shift-q = 'move-node-to-workspace Q'
ctrl-alt-cmd-shift-r = 'move-node-to-workspace R'
ctrl-alt-cmd-shift-s = 'move-node-to-workspace S'
ctrl-alt-cmd-shift-t = 'move-node-to-workspace T'
#ctrl-alt-cmd-shift-u = 'move-node-to-workspace U'
#ctrl-alt-cmd-shift-v = 'move-node-to-workspace V'
ctrl-alt-cmd-shift-w = 'move-node-to-workspace W'
#ctrl-alt-cmd-shift-x = 'move-node-to-workspace X'
#ctrl-alt-cmd-shift-y = 'move-node-to-workspace Y'
#ctrl-alt-cmd-shift-z = 'move-node-to-workspace Z'

ctrl-alt-cmd-m = 'fullscreen'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
ctrl-alt-cmd-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
#alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
ctrl-alt-cmd-esc = 'mode service'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
#backspace = ['close-all-windows-but-current', 'mode main']

# sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
#s = ['layout sticky tiling', 'mode main']

ctrl-alt-cmd-h = ['join-with left', 'mode main']
ctrl-alt-cmd-a = ['join-with down', 'mode main']
ctrl-alt-cmd-o = ['join-with up', 'mode main']
ctrl-alt-cmd-e = ['join-with right', 'mode main']

[[on-window-detected]]
if.app-id = 'com.apple.FaceTime'
run = "layout floating"

