# ───────────────────────────────
# ▶ Startup Settings
# ───────────────────────────────

after-startup-command = [
  'exec-and-forget /opt/homebrew/bin/borders active_color=0xFFF9E2AF inactive_color=0xff494d64 width=5.0'
]
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focus-changed = "move-mouse window-lazy-center"
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = true

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10

# ───────────────────────────────
# ▶ Main Mode
# ───────────────────────────────
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

ctrl-alt-cmd-g = 'fullscreen'
ctrl-alt-cmd-v = 'layout tiles horizontal vertical'
ctrl-alt-cmd-z = 'layout accordion horizontal vertical'
ctrl-alt-cmd-tab = 'workspace-back-and-forth'

ctrl-alt-cmd-quote = '''exec-and-forget osascript -e '
tell application "Safari"
    make new document at end of documents
    activate
end tell'
'''
ctrl-alt-cmd-y = '''exec-and-forget
if pgrep -x "firefox" > /dev/null; then
  /Applications/Firefox.app/Contents/MacOS/firefox --new-window
else
  firefox &
fi
osascript -e 'tell application "Firefox" to activate'
'''
ctrl-alt-cmd-k = '''exec-and-forget osascript -e '
tell application "Finder"
    set target of (make new Finder window) to (path to downloads folder)
    activate
end tell'
'''

#----- Navigation -----
ctrl-alt-cmd-h = 'focus left'
ctrl-alt-cmd-a = 'focus down'
ctrl-alt-cmd-o = 'focus up'
ctrl-alt-cmd-e = 'focus right'

ctrl-alt-cmd-x = 'workspace 1'
ctrl-alt-cmd-m = 'workspace 2'
ctrl-alt-cmd-c = 'workspace 3'
ctrl-alt-cmd-r = 'workspace 4'
ctrl-alt-cmd-t = 'workspace 5'
ctrl-alt-cmd-s = 'workspace 6'
ctrl-alt-cmd-l = 'workspace 7'
ctrl-alt-cmd-d = 'workspace 8'
ctrl-alt-cmd-w = 'workspace 9'

#----- Window Movement -----
ctrl-alt-cmd-shift-h = 'move left'
ctrl-alt-cmd-shift-a = 'move down'
ctrl-alt-cmd-shift-o = 'move up'
ctrl-alt-cmd-shift-e = 'move right'

ctrl-alt-cmd-shift-x = 'move-node-to-workspace 1'
ctrl-alt-cmd-shift-m = 'move-node-to-workspace 2'
ctrl-alt-cmd-shift-c = 'move-node-to-workspace 3'
ctrl-alt-cmd-shift-r = 'move-node-to-workspace 4'
ctrl-alt-cmd-shift-t = 'move-node-to-workspace 5'
ctrl-alt-cmd-shift-s = 'move-node-to-workspace 6'
ctrl-alt-cmd-shift-l = 'move-node-to-workspace 7'
ctrl-alt-cmd-shift-d = 'move-node-to-workspace 8'
ctrl-alt-cmd-shift-w = 'move-node-to-workspace 9'

# ───────────────────────────────
# ▶ Service Mode
# ───────────────────────────────

ctrl-alt-cmd-esc = 'mode service'
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout

h = 'resize width -50'
e = 'resize width +50'
a = 'resize height -50'
o = 'resize height +50'

ctrl-alt-cmd-shift-h = ['join-with left', 'mode main']
ctrl-alt-cmd-shift-a = ['join-with down', 'mode main']
ctrl-alt-cmd-shift-o = ['join-with up', 'mode main']
ctrl-alt-cmd-shift-e = ['join-with right', 'mode main']

[[on-window-detected]]
if.app-id = 'com.apple.FaceTime'
run = "layout floating"
